### ISSUE TITLE
Create a Dockerfile and host on Docker Hub

### ISSUE THREAD

**Issue by bachya** [jamiebegin/metrics2mqtt#2]
Hi! We chatted on your Reddit post. I'm going to take a crack at building the image and will submit a PR in the next several days.

**Comment by bachya** [comment]
This looks like a great GitHub Action to build the Docker image for multiple architectures and push them all to Docker Hub: https://github.com/marketplace/actions/docker-buildx

**Comment by bachya** [comment]
@jamiebegin Now that #3 is merged, let me know if I can be of assistance to you with Docker Hub, using Github Actions to automate pushing new images, etc.

**Comment by jamiebegin** [comment]
Thanks again for the help. I'm very familiar with CI/CD workflows with Jenkins. All the GitHub knobs and whistles are new to me though, as is packaging for PyPi. I'm working through it all. I'll let you know if you can help.

**Comment by bachya** [comment]
FYI, looks like because `python:alpine3.12` is a multi-arch image, you can build images for all of its supported arches via this single Dockerfile. 🥳
